### ISSUE TITLE
Lỗi khi phần tử cần truy cập lại là int 

### ISSUE THREAD

**Issue by bkhnk48** [bkhnk48/pathPlanningSimulation#15]
với phiên bản: https://github.com/bkhnk48/pathPlanningSimulation/commit/929aff61e0729b95c810914ef9a3a103dbff2388
Nếu chạy python3 main.py và tên file nhập vào là simplest.txt thì chương trình lại văng ra lỗi như sau:
```
Traceback (most recent call last):
  File "/Users/leegie/Documents/GitHub/AGV/pathPlanningSimulation/main.py", line 69, in <module>
    simulator.run()
  File "/Users/leegie/anaconda3/lib/python3.11/site-packages/discrevpy/simulator.py", line 246, in run
    next_event[3](*next_event[4], **next_event[5])
  File "/Users/leegie/Documents/GitHub/AGV/pathPlanningSimulation/model/MovingEvent.py", line 28, in process
    self.updateGraph()
  File "/Users/leegie/Documents/GitHub/AGV/pathPlanningSimulation/model/MovingEvent.py", line 15, in updateGraph
    self.graph.update_graph(self.start_node, self.end_node, actual_time)
  File "/Users/leegie/Documents/GitHub/AGV/pathPlanningSimulation/model/Graph.py", line 291, in update_graph
    self.write_to_file()
  File "/Users/leegie/Documents/GitHub/AGV/pathPlanningSimulation/model/Graph.py", line 341, in write_to_file
    file.write(f"a {source_id} {edge[0]} {edge[1].lower} {edge[1].upper} {edge[1].weight}\n")        
                                          ^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by bkhnk48** [comment]
Đã fix xong lỗi này ở bản https://github.com/bkhnk48/pathPlanningSimulation/commit/047d706b22a8f151df0b8d6b24e6b5263a9dc6c1
